export default store = [
  {
    img: 'product1.png',
    title: 'Fifa 19',
    desc: 'Ps4',
    button: 'remove',
    id: 1,
    price: 44,
    Default:1,
    Quan: 0,
    totalPrice: 0,
    Final: 0,
  },
  {
    img: 'product2.png',
    title: 'Glacier White 500GB',
    desc: 'Ps4',
    button: 'remove',
    id: 2,
    Default:1,
    price: 249,
    Quan: 0,
    totalPrice: 0,
    Final: 0,
  },
  {
    img:'download.jpeg',
    title: 'Platinum Headset',
    desc: 'Ps4',
    button: 'remove',
    id: 3,
    Default:1,
    price: 119,
    Quan: 0,
    totalPrice: 0,
    Final: 0,
  },,
  {
    img:'download.jpeg',
    title: 'Coffee beans',
    desc: 'Cofee',
    button: 'remove',
    id: 4,
    price: 80,
    Default:1,
    Quan: 0,
    totalPrice: 0,
    Final: 0,
  },,
  {
    img:'download.jpeg',
    title: 'Lays',
    desc: 'Snacks',
    button: 'remove',
    id: 5,
    price: 40,
    Default:1,
    Quan: 0,
    totalPrice: 0,
    Final: 0,
  },
];
